Change `action` to `bind` in sliders
Was seeing this error
```
Traceback (most recent call last):
  File "/home/stent/MyDocuments/Projects/ComplexFunctionPlotter/ComplexPlotter.py", line 83, in <module>
    realSliderB = slider(pos=vector(-80, -5, 0),
  File "/home/stent/.config/pyenv/versions/3.10.5/lib/python3.10/site-packages/vpython/vpython.py", line 3790, in __init__
    super(slider, self).setup(args)
  File "/home/stent/.config/pyenv/versions/3.10.5/lib/python3.10/site-packages/vpython/vpython.py", line 3504, in setup
    raise AttributeError('bind missing')
AttributeError: bind missing
```

Seems like there is no action param and there is a bind one:
https://github.com/vpython/vpython-jupyter/blob/4e58e2f69758bc42888acf3b1eb967049ed12809/vpython/vpython.py#L3510